name: Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: ['18', '20', '21']
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Update npm
        run: npm i -g npm
        if: ${{ matrix.node-version <= 14 }}
      - name: Install Packages
        run: npm ci
      - name: Build tests tools
        run: npm run build:tests-tools
      - name: Run Tests
        run: npm run test -- -- --forbid-only
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
